//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Type { get; set; }
        public string Manufacturer { get; set; }
        public string Resources_Class { get; set; }
        public string Serial_No { get; set; }
        public string HostName { get; set; }
        public string SpiridonNo { get; set; }
        public string Location { get; set; }
        public string PRNO { get; set; }
        public string PONO { get; set; }
        public string WarrantyStartDate { get; set; }
        public string AgeOfAsset { get; set; }
        public string ExpireBy { get; set; }
        public string Owner { get; set; }
        public string RAM { get; set; }
        public string Storage { get; set; }
        public string Processor { get; set; }
        public string CPUClockSpeed { get; set; }
        public string PhysicalCores { get; set; }
        public string NIC_Count { get; set; }
        public Nullable<bool> ISActive { get; set; }
        public Nullable<bool> ToBeReplaced { get; set; }
        public Nullable<bool> Acknowledge { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
