//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencySubQuestion
    {
        public int SubQuestion_ID { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> SubCategory_Id { get; set; }
        public string SubQuestionText { get; set; }
        public Nullable<int> Project_Id { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsChecked { get; set; }
    
        public virtual CompetencyCategory CompetencyCategory { get; set; }
        public virtual CompetencyLevel CompetencyLevel { get; set; }
        public virtual CompetencyLevel CompetencyLevel1 { get; set; }
        public virtual CompetencyQuestion CompetencyQuestion { get; set; }
        public virtual CompetencySubCategory CompetencySubCategory { get; set; }
        public virtual Project Project { get; set; }
    }
}
