//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competency_Analysis
    {
        public int CompetencyID { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> FeatureCycle_ID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> Level_ID { get; set; }
        public Nullable<int> Base_Value { get; set; }
        public Nullable<int> Goal { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual CompetencyCategory CompetencyCategory { get; set; }
        public virtual CompetencyQuestion CompetencyQuestion { get; set; }
        public virtual User User { get; set; }
        public virtual FeatureCycle FeatureCycle { get; set; }
        public virtual CompetencyLevel CompetencyLevel { get; set; }
        public virtual Project Project { get; set; }
        public virtual CompetencySubCategory CompetencySubCategory { get; set; }
    }
}
