//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetencyQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetencyQuestion()
        {
            this.Competency_Analysis = new HashSet<Competency_Analysis>();
            this.CompetencyMatrices = new HashSet<CompetencyMatrix>();
            this.UserCompetencies = new HashSet<UserCompetency>();
            this.CompetencySubQuestions = new HashSet<CompetencySubQuestion>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public string QuestionExplanation { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> SubCategory_ID { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competency_Analysis> Competency_Analysis { get; set; }
        public virtual CompetencyCategory CompetencyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetencyMatrix> CompetencyMatrices { get; set; }
        public virtual Project Project { get; set; }
        public virtual CompetencySubCategory CompetencySubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCompetency> UserCompetencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetencySubQuestion> CompetencySubQuestions { get; set; }
    }
}
