//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBaseValue
    {
        public int BaseID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> UserName { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> SubCategory_ID { get; set; }
        public Nullable<int> QuestiionID { get; set; }
        public Nullable<int> BaseFC1 { get; set; }
        public Nullable<int> BaseFC2 { get; set; }
        public Nullable<int> BaseFC3 { get; set; }
        public Nullable<int> BaseFC4 { get; set; }
        public Nullable<int> GoalFC1 { get; set; }
        public Nullable<int> GoalFC2 { get; set; }
        public Nullable<int> GoalFC3 { get; set; }
        public Nullable<int> GoalFC4 { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Comment { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
