//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CheckCompetecncy
    {
        public int ProjectID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserName { get; set; }
        public int Category_ID { get; set; }
        public int SubCategory_ID { get; set; }
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public string QuestionExplanation { get; set; }
        public Nullable<int> LEVEL_BASE_FC1 { get; set; }
        public Nullable<int> LEVEL_BASE_FC2 { get; set; }
        public Nullable<int> LEVEL_BASE_FC3 { get; set; }
        public Nullable<int> LEVEL_BASE_FC4 { get; set; }
        public Nullable<int> LEVEL_GOAL_FC1 { get; set; }
        public Nullable<int> LEVEL_GOAL_FC2 { get; set; }
        public Nullable<int> LEVEL_GOAL_FC3 { get; set; }
        public Nullable<int> LEVEL_GOAL_FC4 { get; set; }
        public Nullable<int> Current_Level { get; set; }
    }
}
